### ISSUE TITLE
Upload script timeout

### ISSUE THREAD

**Issue by adibaba** [dice-group/embeddings.cc#47]
The current upload script (index service) breaks with a timeout error, even with upload timeouts with 5 min.

Example:
```
17595000 17600000 17605000 503 Traceback (most recent call last):
  File "/opt/embeddings.cc-2022-07-01b/webservice_index/__init__.py", line 251, in add
    return str(es.get_es().bulk(index=index, body=documents))
  File "/opt/anaconda3/envs/embeddings/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/opt/anaconda3/envs/embeddings/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 693, in bulk
    return self.perform_request(  # type: ignore[return-value]
  File "/opt/anaconda3/envs/embeddings/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/opt/anaconda3/envs/embeddings/lib/python3.10/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/opt/anaconda3/envs/embeddings/lib/python3.10/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionTimeout: Connection timed out

17610000 
real	525m54,202s
user	66m51,776s
sys	2m48,685s
```

There is an API which provides CPU usage. It could be used to dynamically wait.

- https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html
- https://embeddings.cs.upb.de:9200/_nodes/stats
- https://embeddings.cs.upb.de:9200/_nodes/n-CNgjHrRbmTXVhKAxC-NA/stats/process

**Comment by adibaba** [comment]
Added in

- 48fe983bd194f63994c4e1a85d08c0c221648ded
- 3247821220848ab24b08b481b1966495f90a3030
