### ISSUE TITLE
DBpedia embeddings

### ISSUE THREAD

**Issue by adibaba** [dice-group/embeddings.cc#48]
It would be useful to have embeddings of (all) DBpedia entities.
For that, we could use Caligraph or another data source.

# Caligraph DBpedia URIs

For caligraph, embeddings are available here: https://hobbitdata.informatik.uni-leipzig.de/UniKGE/caligraph_dbpedia_procrustes/
The file alignment.json contains 3,745,232 Uri mappings from caligraph to dbpedia.
Example:
```
{
   "http://caligraph.org/resource/Penbontrhydyfoethau": "http://dbpedia.org/resource/Penbontrhydyfoethau",
   "http://caligraph.org/resource/Jacobus_Zegers": "http://dbpedia.org/resource/Jacobus_Zegers",
   "http://caligraph.org/resource/Togainu_no_Chi": "http://dbpedia.org/resource/Togainu_no_Chi",
[...]
   "http://caligraph.org/resource/Bielefeld": "http://dbpedia.org/resource/Bielefeld",
   "http://caligraph.org/resource/Paderborn": "http://dbpedia.org/resource/Paderborn",
```

Additional info and SPARQL endpoint: http://caligraph.org/

For now, we could add DBpedia URIs and related embeddings.

**Comment by adibaba** [comment]
Updated script to add only dbpedia uris+embeddings: https://github.com/dice-group/embeddings.cc/compare/c1303a5..afba6dc

**Comment by adibaba** [comment]
Seems to work, even on timeout:
```

time python3 api/embeddings_cc_index_unikge.py uni_kgs_emb_index 
200

Uploading universal embeddings for /home/wilke/Data/UniKGE/caligraph_dbpedia_procrustes/

Deleting index 200 {'acknowledged': True}

Loading embeddings...

Done!

Creating index 200 {'acknowledged': True, 'shards_acknowledged': True, 'index': 'dbpedia_caligraph'}

Dimensions: 200 

18955733 18960733 18965733 18970733 18975733 18980733 18985733 18990733 18995733 19000733 19005733 19010733 19015733 19020733 19025733 19030733 19035733 19040733 19045733 19050733 19055733 19060733 19065733 19070733 19075733 19080733 19085733 19090733 19095733 19100733 19105733 19110733 19115733 19120733 19125733 19130733 19135733 19140733 19145733 19150733 19155733 19160733 19165733 19170733 19175733 19180733 19185733 19190733 19195733 19200733 19205733 19210733 19215733 19220733 19225733 19230733 19235733 19240733 19245733 19250733 19255733 19260733 19265733 19270733 19275733 19280733 19285733 19290733 19295733 19300733 19305733 19310733 19315733 19320733 19325733 19330733 19335733 19340733 19345733 19350733 19355733 19360733 19365733 19370733 19375733 19380733 19385733 19390733 19395733 19400733 19405733 19410733 19415733 19420733 19425733 19430733 19435733 19440733 19445733 19450733 19455733 19460733 19465733 19470733 19475733 19480733 19485733 19490733 19495733 19500733 19505733 19510733 19515733 19520733 19525733 19530733 19535733 19540733 19545733 19550733 19555733 19560733 19565733 19570733 (s) 19575733 (s) 19580733 19585733 (s) 19590733 (s) 19595733 19600733 19605733 19610733 19615733 19620733 19625733 19630733 19635733 19640733 19645733 19650733 19655733 19660733 19665733 19670733 19675733 19680733 19685733 19690733 19695733 19700733 19705733 19710733 19715733 19720733 19725733 19730733 19735733 19740733 19745733 19750733 19755733 19760733 19765733 19770733 19775733 19780733 19785733 19790733 19795733 19800733 19805733 19810733 19815733 19820733 19825733 19830733 19835733 19840733 19845733 19850733 19855733 19860733 19865733 19870733 19875733 19880733 19885733 19890733 19895733 19900733 19905733 19910733 19915733 19920733 19925733 19930733 19935733 19940733 19945733 19950733 19955733 19960733 19965733 19970733 19975733 19980733 19985733 19990733 19995733 20000733 20005733 20010733 20015733 20020733 20025733 20030733 20035733 20040733 20045733 20050733 20055733 20060733 20065733 20070733 20075733 20080733 20085733 20090733 20095733 20100733 20105733 20110733 20115733 20120733 20125733 20130733 20135733 20140733 20145733 20150733 20155733 20160733 20165733 20170733 20175733 20180733 20185733 (s) 20190733 (s) 20195733 20200733 (s) 20205733 (s) 20210733 20215733 20220733 20225733 20230733 20235733 20240733 20245733 20250733 20255733 20260733 20265733 20270733 20275733 20280733 20285733 20290733 20295733 20300733 20305733 20310733 20315733 20320733 20325733 20330733 20335733 20340733 20345733 20350733 20355733 20360733 20365733 20370733 20375733 20380733 20385733 20390733 20395733 20400733 20405733 20410733 20415733 20420733 20425733 20430733 20435733 20440733 20445733 20450733 20455733 20460733 20465733 20470733 20475733 20480733 20485733 20490733 20495733 20500733 20505733 20510733 20515733 20520733 20525733 20530733 20535733 20540733 20545733 20550733 20555733 20560733 20565733 20570733 20575733 20580733 20585733 20590733 20595733 20600733 20605733 20610733 20615733 20620733 20625733 20630733 20635733 20640733 20645733 20650733 20655733 20660733 20665733 20670733 20675733 20680733 20685733 20690733 20695733 20700733 20705733 20710733 20715733 20720733 20725733 20730733 20735733 20740733 20745733 20750733 20755733 20760733 20765733 20770733 20775733 20780733 20785733 20790733 20795733 20800733 20805733 (s) 20810733 (s) 20815733 20820733 (s) 20825733 (s) 20830733 20835733 20840733 20845733 20850733 20855733 20860733 20865733 20870733 20875733 20880733 20885733 20890733 20895733 20900733 20905733 20910733 20915733 20920733 20925733 20930733 20935733 20940733 20945733 20950733 20955733 20960733 20965733 20970733 20975733 20980733 20985733 20990733 20995733 21000733 21005733 21010733 21015733 21020733 21025733 21030733 21035733 21040733 21045733 21050733 21055733 21060733 21065733 21070733 21075733 21080733 21085733 21090733 21095733 21100733 21105733 21110733 21115733 21120733 21125733 21130733 21135733 21140733 21145733 21150733 21155733 21160733 21165733 21170733 21175733 21180733 21185733 21190733 21195733 21200733 21205733 21210733 21215733 21220733 21225733 21230733 21235733 21240733 21245733 21250733 21255733 21260733 21265733 21270733 21275733 21280733 21285733 21290733 21295733 21300733 21305733 21310733 21315733 21320733 21325733 21330733 21335733 21340733 21345733 21350733 21355733 21360733 21365733 21370733 21375733 21380733 21385733 21390733 21395733 21400733 21405733 21410733 21415733 21420733 21425733 (s) 21430733 (s) 21435733 (s) 21440733 (s) 21445733 21450733 21455733 21460733 21465733 21470733 21475733 21480733 21485733 21490733 21495733 21500733 21505733 21510733 21515733 21520733 21525733 21530733 21535733 21540733 21545733 21550733 21555733 21560733 21565733 21570733 21575733 21580733 21585733 21590733 21595733 21600733 21605733 21610733 21615733 21620733 21625733 21630733 21635733 21640733 21645733 21650733 21655733 21660733 21665733 21670733 21675733 21680733 21685733 21690733 21695733 21700733 21705733 21710733 21715733 21720733 21725733 21730733 21735733 21740733 21745733 21750733 21755733 21760733 21765733 21770733 21775733 21780733 21785733 21790733 21795733 21800733 21805733 21810733 21815733 21820733 21825733 21830733 21835733 21840733 21845733 21850733 21855733 21860733 21865733 21870733 21875733 21880733 21885733 21890733 21895733 21900733 21905733 21910733 21915733 21920733 21925733 21930733 21935733 21940733 21945733 21950733 21955733 21960733 21965733 21970733 21975733 21980733 21985733 21990733 21995733 22000733 22005733 22010733 22015733 22020733 22025733 22030733 22035733 22040733 (s) 22045733 (s) 22050733 22055733 (s) 22060733 (s) 22065733 22070733 22075733 22080733 22085733 22090733 22095733 22100733 22105733 22110733 22115733 22120733 22125733 22130733 22135733 22140733 22145733 22150733 22155733 22160733 22165733 22170733 22175733 22180733 22185733 22190733 22195733 22200733 22205733 22210733 22215733 22220733 22225733 22230733 22235733 22240733 22245733 22250733 22255733 22260733 22265733 22270733 22275733 22280733 22285733 22290733 22295733 22300733 22305733 22310733 22315733 22320733 22325733 22330733 22335733 22340733 22345733 22350733 22355733 22360733 22365733 22370733 22375733 22380733 22385733 22390733 22395733 22400733 22405733 22410733 22415733 22420733 22425733 22430733 22435733 22440733 22445733 22450733 22455733 22460733 22465733 22470733 22475733 22480733 22485733 22490733 22495733 22500733 22505733 22510733 22515733 22520733 22525733 22530733 22535733 22540733 22545733 22550733 22555733 22560733 22565733 22570733 22575733 22580733 22585733 22590733 22595733 22600733 22605733 22610733 22615733 22620733 22625733 22630733 22635733 22640733 22645733 22650733 22655733 22660733 (s) 22665733 (s) 22670733 (s) 22675733 (s) 22680733 22685733 22690733 22695733 0 Traceback (most recent call last):
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/backends/sync.py", line 26, in read
    return self._sock.recv(max_bytes)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_transports/default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 253, in handle_request
    raise exc
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 90, in handle_request
    return self._connection.handle_request(request)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 102, in handle_request
    raise exc
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 81, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 172, in _receive_event
    data = self._network_stream.read(
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/backends/sync.py", line 24, in read
    with map_exceptions(exc_map):
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wilke/git/embeddings.cc/api/embeddings_cc_index_unikge.py", line 150, in <module>
    response = embeddings_cc_index.count(es_index)
  File "/home/wilke/git/embeddings.cc/api/embeddings_cc_index.py", line 42, in count
    return httpx.get(self.webservice_url + '/count', params={'index': index})
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_api.py", line 189, in get
    return request(
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_api.py", line 100, in request
    return client.request(
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_client.py", line 802, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_client.py", line 889, in send
    response = self._send_handling_auth(
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_client.py", line 917, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_client.py", line 990, in _send_single_request
    response = transport.handle_request(request)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_transports/default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/wilke/.anaconda3/envs/embeddings/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out

real	124m25,874s
user	14m39,387s
sys	0m54,706s

```
