### ISSUE TITLE
Conda / WSGI after reinstallation

### ISSUE THREAD

**Issue by adibaba** [dice-group/embeddings.cc#51]
- Issue: Website not running
- Re-installed conda, formerly  `/opt/anaconda3` now `/data/anaconda/`
- new conda installation modified bashrc. copied code from user wilke to user embeddings.
- `sudo journalctl -u embeddings.service -b` had error. Resolved afterwards.
- added uwsgi to requirements. Installed: `conda install -c conda-forge --file requirements.txt`
- site itself works at http://embeddings.cs.upb.de:5000/ with:

```
sudo -u embeddings -s
conda activate embeddings
cd /opt/embeddings
flask run --host=0.0.0.0
```

Currently:

`sudo journalctl -u embeddings.service -b` lists: `ModuleNotFoundError: No module named 'flask_cors'`

and

`uwsgi --plugin python3  -H /data/anaconda --mount /=webservice_public/wsgi.py --socket /tmp/______embeddings.sock --chmod-socket=666 --thunder-lock --master --enable-threads --manage-script-name`

```
Python path configuration:
  PYTHONHOME = '/data/anaconda'
  PYTHONPATH = (not set)
  program name = '/data/anaconda/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/data/anaconda/bin/python'
  sys.base_prefix = '/data/anaconda'
  sys.base_exec_prefix = '/data/anaconda'
  sys.platlibdir = 'lib'
  sys.executable = '/data/anaconda/bin/python'
  sys.prefix = '/data/anaconda'
  sys.exec_prefix = '/data/anaconda'
  sys.path = [
    '/data/anaconda/lib/python310.zip',
    '/data/anaconda/lib/python3.10',
    '/data/anaconda/lib/python3.10/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fe9ec143300 (most recent call first):
  <no Python frame>

```

**Comment by adibaba** [comment]
- old installation: https://github.com/dice-group/embeddings.cc/blob/5908fd66eec2b0737872c9f4c7284e0bb2b4d8a5/docs/vm.md#packages-installation
- that modified file `/root/.bashrc` -> still using `/opt/anaconda3/`

**Comment by adibaba** [comment]
```
sudo journalctl -u embeddings.service -b
[sudo] password for wilke: 
-- Journal begins at Tue 2023-01-31 14:44:26 CET, ends at Tue 2023-01-31 14:47:49 CET. --
Jan 31 14:44:36 embeddings systemd[1]: Started embeddings uwsgi.
Jan 31 14:44:36 embeddings uwsgi[824]: [uWSGI] getting INI configuration from /opt/uwsgi.ini
Jan 31 14:44:36 embeddings uwsgi[824]: *** Starting uWSGI 2.0.19.1-debian (64bit) on [Tue Jan 31 14:44:36 2023] ***
Jan 31 14:44:36 embeddings uwsgi[824]: compiled with version: 10.2.1 20210110 on 11 June 2021 09:08:33
Jan 31 14:44:36 embeddings uwsgi[824]: os: Linux-5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21)
Jan 31 14:44:36 embeddings uwsgi[824]: nodename: embeddings
Jan 31 14:44:36 embeddings uwsgi[824]: machine: x86_64
Jan 31 14:44:36 embeddings uwsgi[824]: clock source: unix
Jan 31 14:44:36 embeddings uwsgi[824]: pcre jit disabled
Jan 31 14:44:36 embeddings uwsgi[824]: detected number of CPU cores: 4
Jan 31 14:44:36 embeddings uwsgi[824]: current working directory: /opt/embeddings.cc-2022-07-20
Jan 31 14:44:36 embeddings uwsgi[824]: detected binary path: /usr/bin/uwsgi-core
Jan 31 14:44:36 embeddings uwsgi[824]: your processes number limit is 128310
Jan 31 14:44:36 embeddings uwsgi[824]: your memory page size is 4096 bytes
Jan 31 14:44:36 embeddings uwsgi[824]: detected max file descriptor number: 1024
Jan 31 14:44:36 embeddings uwsgi[824]: lock engine: pthread robust mutexes
Jan 31 14:44:36 embeddings uwsgi[824]: thunder lock: enabled
Jan 31 14:44:36 embeddings uwsgi[824]: uwsgi socket 0 bound to UNIX address /tmp/embeddingscc.sock fd 3
Jan 31 14:44:36 embeddings uwsgi[824]: Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
Jan 31 14:44:36 embeddings uwsgi[824]: Set PythonHome to /data/anaconda/
Jan 31 14:44:37 embeddings uwsgi[824]: Python main interpreter initialized at 0x55c583b590a0
Jan 31 14:44:37 embeddings uwsgi[824]: python threads support enabled
Jan 31 14:44:37 embeddings uwsgi[824]: your server socket listen backlog is limited to 100 connections
Jan 31 14:44:37 embeddings uwsgi[824]: your mercy for graceful operations on workers is 60 seconds
Jan 31 14:44:37 embeddings uwsgi[824]: mapped 145872 bytes (142 KB) for 1 cores
Jan 31 14:44:37 embeddings uwsgi[824]: *** Operational MODE: single process ***
Jan 31 14:44:37 embeddings uwsgi[824]: mounting webservice_public/wsgi.py on /
Jan 31 14:44:38 embeddings uwsgi[824]: Traceback (most recent call last):
Jan 31 14:44:38 embeddings uwsgi[824]:   File "webservice_public/wsgi.py", line 2, in <module>
Jan 31 14:44:38 embeddings uwsgi[824]:     from webservice_public import *
Jan 31 14:44:38 embeddings uwsgi[824]:   File "./webservice_public/__init__.py", line 6, in <module>
Jan 31 14:44:38 embeddings uwsgi[824]:     from flask_cors import cross_origin
Jan 31 14:44:38 embeddings uwsgi[824]: ModuleNotFoundError: No module named 'flask_cors'
Jan 31 14:44:38 embeddings systemd[1]: embeddings.service: Main process exited, code=exited, status=22/n/a
Jan 31 14:44:38 embeddings systemd[1]: embeddings.service: Failed with result 'exit-code'.
```
`conda list` does not list flask_cors for environment base. But it is installed for environment embeddings.  
-> `conda activate base` ; `cd /opt/embeddings` ; `conda install -c conda-forge --file requirements.txt`

**Comment by adibaba** [comment]
installation of packages for base environment
```
conda install -c conda-forge --file requirements.txt
Collecting package metadata (current_repodata.json): done                                                                                                                                                            
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
```
tried `conda update --all --yes` (https://stackoverflow.com/a/68542234)  
-> user embeddings can not write -> tried with wilke -> update worked

**Comment by adibaba** [comment]
-> solved with packet installation in base environment
